apps/camps/urls.py
from django.urls import path

from apps.camps.views import index, camp_list, camp_detail, cabinet

app_name = 'camps'
urlpatterns = [
    path('', index, name='index'),
    path('camps_list/', camp_list, name='camps_list'),
    path('camps_detail/<int:pk>/', camp_detail, name='camps_detail'),
    path('cabinet/', cabinet, name='cabinet'),
]

apps/one_id_auth/urls.py
from django.urls import path
from apps.one_id_auth.views import eauth, eauthcallback, Login

app_name = 'one_id_auth'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('eauth/', eauth, name='eauth'),
    path('eauthcallback/', eauthcallback, name='eauthcallback'),
]

summer_camps/urls.py
from django.contrib import admin
from django.urls import path, include
from summer_camps import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('django_admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('apps.camps.urls')),
    path('', include('apps.telegram_auth.urls')),
    path('', include('apps.admin_dashboard.urls')),
    path('', include('apps.user.urls')),
    path('', include('apps.reservation.urls')),
    path('', include('apps.one_id_auth.urls')),
    path('', include('apps.stats.urls')),
)
urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/admin_dashboard/views/camps_list.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Sum, OuterRef, Subquery, IntegerField
from django.views.generic import ListView

from apps.camps.models import Camp
from apps.user.models import User


class CampsListView(LoginRequiredMixin, ListView):
    login_url = '/login'
    model = Camp
    queryset = Camp.objects.all()
    template_name = 'admin_interface/camps_list.html'
    context_object_name = 'all_camps'

    def get_queryset(self):
        """
        Filter camps list, show to the user
        only camps within user's region
        :return: queryset
        """
        get_user_id = self.request.user.id
        get_region = User.objects.get(id=get_user_id).city_id

        camps = Camp.objects.filter(region__city_id=get_region)
        sum_camp_capacity = camps.annotate(total_camp_capacity_new=Sum('squad__capacity')) \
            .filter(pk=OuterRef('pk'))

        count_shifts = camps.annotate(number_of_shifts_new=Count('shift')) \
            .filter(pk=OuterRef('pk'))

        count_squads = camps.annotate(number_of_squads_new=Count('squad')) \
            .filter(pk=OuterRef('pk'))

        camps = camps.annotate(total_camp_capacity=Subquery(sum_camp_capacity.values('total_camp_capacity_new'),
                                                            output_field=IntegerField()))

        camps = camps.annotate(total_shifts=Subquery(count_shifts.values('number_of_shifts_new'),
                                                     output_field=IntegerField()))

        camps = camps.annotate(total_squads=Subquery(count_squads.values('number_of_squads_new'),
                                                     output_field=IntegerField()))

        return camps

templates/other/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "other/components/head.html" %}
<body>

{% block content %}{% endblock %}

{% include "other/components/footer.html" %}
</body>
</html>

templates/other/camps-list.html
{% extends 'other/base.html' %}
{% load static %}

{% block content %}

    <section class="camps-banner">
        <div class="camps-banner-img">
            <img src="{% static 'front/img/pbanner.png' %}">
        </div>
        {% include "other/components/navbar.html" %}
        <div class="enter text-center">
            <div class="container">
                <div class="spring">
                    <span>Сезон: 2021</span>
                </div>
                <div class="enter-text">
                    <span>Детские летние лагеря<br> Узбекистана</span>
                </div>
            </div>
        </div>
        <div class="select pb-5">
            <div class="container">
                <div class="select-title">
                    <span>Подберите лучший вариант для вашего ребенка</span>
                </div>
                <div class="select-form">
                    <form>
                        <div class="select-div">
                            <select>
                                <option>Все области</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                            <span class="select-line"></span>
                        </div>
                        <div class="select-div">
                            <select>
                                <option>Все районы</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                            <span class="select-line"></span>
                        </div>
                        <div class="select-div">
                            <select>
                                <option>Возраст</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                            <span class="select-line"></span>
                        </div>
                        <div class="select-div">
                            <select>
                                <option>Все характеристики</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                            <span class="select-line"></span>
                        </div>
                        <div class="select-submit">
                            <button>
                                <span>Подобрать</span>
                                <img src="{% static 'front/img/select.png' %}">
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <section class="pcamps-section">
        <div class="pcamps-container container">
            <div class="result">
                <span class="result-text">Показаны результаты:</span>
                <span class="result-number">10</span>
                <span class="result-text">из</span>
                <span class="result-number">358</span>
            </div>
            {% for camp in camps %}
                <div class="pcamps">
                    <div class="camps-in">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="camps-img">
                                    <a href="{% url 'camps:camps_detail' camp.id %}">
                                        <div class="camps-img-in">
                                            <img src="{% static 'front/img/camp1.jpg' %}">
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="camps-right">
                                    <div class="camps-title">
                                        <a href="{% url 'camps:camps_detail' camp.id %}">{{ camp.name }}</a>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="camps-data">
                                            <img src="{% static 'front/img/age.png' %}">
                                            <span class="left">Возраст:</span>
                                            <span class="right">от 8 до 14 лет</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="camps-data">
                                            <img src="{% static 'front/img/day.png' %}">
                                            <span class="left">Смена:</span>
                                            <span class="right">21 день</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="camps-data">
                                    <img src="{% static 'front/img/address.png' %}">
                                    <span class="left">Адрес:</span>
                                    <span class="right">{{ camp.address }}</span>
                                </div>
                                <div class="camps-maps-link">
                                    <a href="#">
                                        <span>Посмотреть на карте</span>
                                        <img src="{% static 'front/img/red-right.png' %}">
                                    </a>
                                </div>
                                <div class="camps-data">
                                    <img src="{% static 'front/img/price.png' %}">
                                    <span class="left">Цена:</span>
                                    <span class="price">от {{ camp.cost }} сум</span>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="camps-rate">
                                            <div class="rate">
                                                <input type="radio" id="star5" name="rate" value="5"/>
                                                <label for="star5" title="text5">5 stars</label>
                                                <input type="radio" id="star4" name="rate" value="4"/>
                                                <label for="star4" title="text4">4 stars</label>
                                                <input type="radio" id="star3" name="rate" value="3"/>
                                                <label for="star3" title="text3">3 stars</label>
                                                <input type="radio" id="star2" name="rate" value="2"/>
                                                <label for="star2" title="text2">2 stars</label>
                                                <input type="radio" id="star1" name="rate" value="1"/>
                                                <label for="star1" title="text1">1 star</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="camps-read">
                                            <a href="{% url 'camps:camps_detail' camp.id %}">
                                                <span>Подробнее</span>
                                                <img src="{% static 'front/img/white-right.png' %}">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="my-pagination">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="" href="#" aria-label="Previous">
                                <img src="{% static 'front/img/p-left.png' %}">
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="" href="#" aria-label="Next">
                                <img src="{% static 'front/img/p-right.png' %}">
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
{% endblock %}

templates/other/login.html
{% extends 'other/base.html' %}
{% load static %}

{% block content %}
    <section class="banner-login">
        <div class="banner-img">
            <img src="{% static 'front/img/banner.jpg' %}">
        </div>
        {% include 'other/components/navbar.html' %}
        <div class="one-id">
            <div class="one-id-in">
                <a href="{% url 'one_id_auth:eauth' %}">
                    <img src="{% static 'front/img/avatar.png' %}">
                </a>
            </div>
            <div class="one-id-text text-center mt-3">
                <a href="{% url 'one_id_auth:eauth' %}"
                   style="color: aliceblue; text-decoration: none; font-weight: 600;">
                    <span>Пройдите авторизацию через OneID</span>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

templates/other/reservation_test.html
{% extends 'other/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="POST" action="">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="row form-row spacer">
                <div class="col-2">
                    <label>Bola</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{ form.name }}
                        {{ form.gender }}
                        {{ form.age }}
                        <select class="form-select" aria-label="Default select example" name="shift">
                            {% for shift in shifts %}
                                <option value="{{ shift.id }}">{{ shift }}</option>
                            {% endfor %}
                        </select>

                        <div class="input-group-append">
                            <button class="btn btn-success add-form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row spacer">
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-block btn-primary">Create</button>
            </div>
        </div>
    </form>
{% endblock %}