apps/camps/urls.py
from django.urls import path

from apps.camps.views import index, camp_list, camp_detail, cabinet

app_name = 'camps'
urlpatterns = [
    path('', index, name='index'),
    path('camps_list/', camp_list, name='camps_list'),
    path('camps_detail/<int:pk>/', camp_detail, name='camps_detail'),
    path('cabinet/', cabinet, name='cabinet'),
]

summer_camps/urls.py
from django.contrib import admin
from django.urls import path, include
from summer_camps import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('django_admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('apps.camps.urls')),
    path('', include('apps.telegram_auth.urls')),
    path('', include('apps.admin_dashboard.urls')),
    path('', include('apps.user.urls')),
    path('', include('apps.reservation.urls')),
    path('', include('apps.one_id_auth.urls')),
    path('', include('apps.stats.urls')),
)
urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/other/components/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>Oromgohlar</title>
    <link rel="icon" href="{% static 'front/img/logo.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/scrollCue.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'front/css/custom.css' %}">
</head>

templates/other/components/navbar.html
{% load static %}
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="logo">
                    <a href="/">
                        <img src="{% static 'front/img/logo.png' %}">
                    </a>
                </div>
            </div>
            <div class="col-md-10">
                <div class="menu-cab-lang">
                    <div class="menu">
                        <nav class="navbar navbar-expand-xl navbar-light">
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Главная</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">О сервисе</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Родителям</a>
                                    </li>

                                    <li class="nav-item dropdown">
                                        <a class="nav-link" href="#" id="navbarDropdown" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Способы оплаты
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="#">Action</a>
                                            <a class="dropdown-item" href="#">Another action</a>
                                            <a class="dropdown-item" href="#">Something else here</a>
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Контакты</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                    <div class="cab-lang">
                        {% if request.user.is_authenticated %}
                            <div class="cabinet">
                                <div class="dropdown">
                                    <button class="cabinet-in" type="button" id="dropdownMenuButton"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span>{{ request.user.username }}</span>
                                        <img src="{% static 'front/img/account.png' %}">
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{% url 'camps:cabinet' %}">
                                            <img src="{% static 'front/img/cab1.png' %}">
                                            <span>Личный кабинет</span>
                                        </a>
                                        <a class="dropdown-item" href="{% url 'logout' %}">
                                            <img src="{% static 'front/img/cab5.png' %}">
                                            <span>Выйти</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="cabinet">
                                <a href="/login" class="cabinet-in d-inline-block">
                                    <span>Вход в кабинет</span>
                                    <img src="{% static 'front/img/account.png' %}">
                                </a>
                            </div>
                        {% endif %}
                        <div class="lang">
                            <div class="lang-in">
                                <button>
                                    <span>Ру</span>
                                </button>
                                <ul>
                                    <li>
                                        <a href="/">Ру</a>
                                    </li>
                                    <li>
                                        <a href="/uz">Ўз</a>
                                    </li>
                                    <li>
                                        <a href="/oz">O'z</a>
                                    </li>
                                    <li>
                                        <a href="/en">En</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/other/components/sidebar.html
{% load static %}