apps/reservation/urls.py
from django.urls import path

from apps.reservation.views import ReservationsListView

urlpatterns = [
    path('reservations/', ReservationsListView.as_view(), name='reservations')
]

apps/stats/urls.py
from django.urls import path

from apps.stats.views import StatsTestView

urlpatterns = [
    path('stats/', StatsTestView.as_view(), name='stats')
]

summer_camps/urls.py
from django.contrib import admin
from django.urls import path, include
from summer_camps import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('django_admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('apps.camps.urls')),
    path('', include('apps.telegram_auth.urls')),
    path('', include('apps.admin_dashboard.urls')),
    path('', include('apps.user.urls')),
    path('', include('apps.reservation.urls')),
    path('', include('apps.one_id_auth.urls')),
    path('', include('apps.stats.urls')),
)
urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/camps/models.py
from django.db import models
from django.db.models import CASCADE, PROTECT

from apps.core.constants.seasons import CAMP_SEASONS
from apps.core.models.base_model import BaseModel
from apps.core.constants.camp_children_gender import SQUAD_CHILDREN_GENDER
# from apps.user.models import User
from apps.core.constants.squad_type import SQUAD_STRUCTURE_TYPE
from apps.core.constants.leader_type import LEADER_TYPES
from apps.core.constants.user_child_gender import CHILD_GENDER


class Advantage(BaseModel):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Advantage'
        verbose_name_plural = 'Advantages'


class Camp(BaseModel):
    region = models.ForeignKey('locations.Region', PROTECT)
    advantages = models.ManyToManyField(Advantage)

    name = models.CharField(max_length=256)
    main_description = models.TextField(null=True, blank=True)
    about_description = models.TextField(null=True, blank=True)
    nutrition_description = models.TextField(null=True, blank=True)
    program_description = models.TextField(null=True, blank=True)

    address = models.CharField(max_length=255)
    cost = models.PositiveIntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    total_capacity = models.PositiveIntegerField(default=0, null=True, blank=True)
    date_opened = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name


class CampSeason(BaseModel):
    camp = models.ForeignKey(Camp, CASCADE)
    season = models.CharField(max_length=255, choices=CAMP_SEASONS)

    def __str__(self):
        return '{0} (Season: {1})'.format(self.camp, self.season)

    class Meta:
        unique_together = ('camp', 'season')


class Shift(BaseModel):
    camp = models.ForeignKey(Camp, CASCADE)

    number = models.PositiveIntegerField()
    capacity = models.PositiveIntegerField(null=True, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return '{0} {1} shift'.format(self.camp.name, self.number)


class Squad(BaseModel):
    camp = models.ForeignKey(Camp, CASCADE, null=True, blank=True)

    gender = models.CharField(max_length=50, choices=SQUAD_CHILDREN_GENDER)
    squad_structure_type = models.CharField(max_length=50, choices=SQUAD_STRUCTURE_TYPE)
    number = models.PositiveIntegerField()
    from_age = models.PositiveIntegerField()
    until_age = models.PositiveIntegerField()
    capacity = models.PositiveIntegerField()

    def __str__(self):
        return '{0}'.format(self.number)

    class Meta:
        unique_together = ('camp', 'number')


class CampImage(BaseModel):
    camp = models.ForeignKey(Camp, CASCADE)
    image = models.FileField(upload_to='')
    is_primary = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.image}'


class Placement(BaseModel):
    squad = models.ForeignKey(Squad, CASCADE)
    shift = models.ForeignKey(Shift, CASCADE)

    child_first_name = models.CharField(max_length=255)
    child_last_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=55, choices=CHILD_GENDER)
    certificate_of_birth = models.CharField(max_length=55)
    bunk = models.CharField(max_length=255)
    birth_year = models.DateField()

    def __str__(self):
        return self.certificate_of_birth


class SquadLeaders(BaseModel):
    leader = models.ForeignKey('user.User', CASCADE, null=True, blank=True)
    squad = models.ForeignKey(Squad, CASCADE)
    shift = models.ForeignKey(Shift, CASCADE)

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    leader_type = models.CharField(max_length=55, choices=LEADER_TYPES)
    phone_number = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

apps/reservation/models.py
from django.contrib.auth.models import User
from django.db import models

from apps.core.models.base_model import BaseModel
from summer_camps import settings


class TicketReservation(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    camp = models.ForeignKey('camps.Camp', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    expiration_date = models.CharField(max_length=255, null=True, blank=True)
    is_expired = models.CharField(max_length=255, null=True, blank=True)

apps/stats/models.py
from django.db import models

# Create your models here.

apps/admin_dashboard/forms/update_advantage.py
from django import forms

from apps.camps.models import Advantage


class UpdateAdvantageModelForm(forms.ModelForm):
    class Meta:
        model = Advantage
        fields = '__all__'

apps/admin_dashboard/forms/update_bunk.py
from django import forms

from apps.camps.models import Bunk


class UpdateBunkModelForm(forms.ModelForm):
    class Meta:
        model = Bunk
        fields = '__all__'

apps/admin_dashboard/forms/update_camp.py
from django import forms

from apps.camps.models import Camp


class UpdateCampForm(forms.ModelForm):
    class Meta:
        model = Camp
        fields = '__all__'
        exclude = ('rating',
                   'total_capacity',
                   'rating')

apps/admin_dashboard/forms/update_shift.py
from django import forms

from apps.camps.models import Shift


class UpdateShiftModelForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = '__all__'
        exclude = ('camp',)

apps/admin_dashboard/forms/update_squad.py
from django import forms

from apps.camps.models import Squad


class UpdateSquadModelForm(forms.ModelForm):
    class Meta:
        model = Squad
        fields = '__all__'

apps/reservation/forms.py
from django import forms
from django.forms import formset_factory, modelformset_factory

from apps.reservation.models import TicketReservation
from apps.user.models import Child
from apps.camps.models import Shift

MALE = 'M'
FEMALE = 'F'
GENDERS = [
    (MALE, 'O\'gil'),
    (FEMALE, 'Qiz'),
]


class ReservationForm(forms.ModelForm):
    class Meta:
        model = TicketReservation
        fields = ('name',)
        labels = {
            'name': 'Book Name'
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Book Name here'
            }
            )
        }


class ChildModelForm(forms.ModelForm):
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    gender = forms.ChoiceField(
        choices=GENDERS,
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    age = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Child
        fields = (
            'name',
            'gender',
            'age',
            'shift',
        )

    # def __init__(self, camp, *args, **kwargs):
    #     super(ChildModelForm, self).__init__(*args, **kwargs)
    #     self.fields['camp'].queryset = Shift.objects.filter(camp=camp)


# ReservationFormSet = modelformset_factory(
#     Child,
#     fields=('name', 'gender', 'age', 'shift'),
#     extra=1,
#     widgets={
#         'name': forms.TextInput(attrs={
#             'class': 'form-control',
#             'placeholder': 'FISH'
#         }),
#         'gender': forms.TextInput(attrs={
#             'class': 'form-control',
#             'placeholder': 'jinsi'
#         }),
#         'age': forms.TextInput(attrs={
#             'class': 'form-control',
#             'placeholder': 'Yoshi'
#         }),
#     }
# )

ReservationFormSet = modelformset_factory(
    Child,
    form=ChildModelForm,
)

apps/admin_dashboard/views/add_placement.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView

from apps.admin_dashboard.forms.create_placement import CreatePlacementForm
from apps.camps.models import Placement, Squad, Shift


class PlacementCreateView(LoginRequiredMixin, CreateView):
    model = Placement
    template_name = 'admin_interface/add_placement.html'
    form_class = CreatePlacementForm
    success_url = '/placements'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        get_user_camp = self.request.user.camp.id
        context['own_camp_squads_list'] = Squad.objects.filter(camp_id=get_user_camp)
        context['own_camp_shift_list'] = Shift.objects.filter(camp_id=get_user_camp)
        return context

apps/admin_dashboard/views/camp_detail.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class CampDetail(LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'admin_interface/camp_detail.html'

apps/admin_dashboard/views/camps_list.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Sum, OuterRef, Subquery, IntegerField
from django.views.generic import ListView

from apps.camps.models import Camp
from apps.user.models import User


class CampsListView(LoginRequiredMixin, ListView):
    login_url = '/login'
    model = Camp
    queryset = Camp.objects.all()
    template_name = 'admin_interface/camps_list.html'
    context_object_name = 'all_camps'

    def get_queryset(self):
        """
        Filter camps list, show to the user
        only camps within user's region
        :return: queryset
        """
        get_user_id = self.request.user.id
        get_region = User.objects.get(id=get_user_id).city_id

        camps = Camp.objects.filter(region__city_id=get_region)
        sum_camp_capacity = camps.annotate(total_camp_capacity_new=Sum('squad__capacity')) \
            .filter(pk=OuterRef('pk'))

        count_shifts = camps.annotate(number_of_shifts_new=Count('shift')) \
            .filter(pk=OuterRef('pk'))

        count_squads = camps.annotate(number_of_squads_new=Count('squad')) \
            .filter(pk=OuterRef('pk'))

        camps = camps.annotate(total_camp_capacity=Subquery(sum_camp_capacity.values('total_camp_capacity_new'),
                                                            output_field=IntegerField()))

        camps = camps.annotate(total_shifts=Subquery(count_shifts.values('number_of_shifts_new'),
                                                     output_field=IntegerField()))

        camps = camps.annotate(total_squads=Subquery(count_squads.values('number_of_squads_new'),
                                                     output_field=IntegerField()))

        return camps

apps/admin_dashboard/views/dashboard.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class DashboardTemplateView(LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'admin_interface/dashboard.html'

apps/admin_dashboard/views/update_advantage.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView

from apps.admin_dashboard.forms.update_advantage import UpdateAdvantageModelForm
from apps.camps.models import Advantage


class AdvantageUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Advantage
    template_name = 'admin_interface/update_advantage.html'
    success_url = '/settings/advantages/'
    form_class = UpdateAdvantageModelForm

apps/admin_dashboard/views/update_camp.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView

from apps.admin_dashboard.forms.update_camp import UpdateCampForm
from apps.camps.models import Camp, CampImage, Advantage
from apps.locations.models import Region
from apps.main.models import PhoneNumber
from apps.user.models import User


class CampUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Camp
    template_name = 'admin_interface/update_camp.html'
    success_url = '/camps/list/'
    form_class = UpdateCampForm

    def form_valid(self, form):
        get_images = self.request.FILES.getlist('images')
        get_phone_numbers = self.request.POST.getlist('phone_number')

        camp = form.save(commit=False)
        camp.save()
        for image in get_images:
            CampImage.objects.create(
                camp_id=camp.id,
                image=image
            )
        PhoneNumber.objects.filter(camp_id=camp.id).delete()
        for phone_number in get_phone_numbers:
            PhoneNumber.objects.create(
                camp_id=camp.pk,
                number=phone_number
            )
        return redirect('/camps/list/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get linked to the user regions list
        user_id_from_request = self.request.user.id
        get_user_from_db = User.objects.get(id=user_id_from_request)
        get_user_linked_city_id = get_user_from_db.city_id
        regions_list = Region.objects.filter(city_id=get_user_linked_city_id)

        advantages = Advantage.objects.all()
        context['regions'] = regions_list
        context['advantages'] = advantages
        return context

apps/admin_dashboard/views/update_shift.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView

from apps.admin_dashboard.forms.update_shift import UpdateShiftModelForm
from apps.camps.models import Shift


class ShiftUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Shift
    template_name = 'admin_interface/update_shift.html'
    form_class = UpdateShiftModelForm

    def get_success_url(self):
        get_shift = Shift.objects.get(id=self.object.id)
        camp_id = get_shift.camp_id
        return '/shifts/list/?camp={}'.format(camp_id)

apps/admin_dashboard/views/update_squad.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView

from apps.admin_dashboard.forms.update_squad import UpdateSquadModelForm
from apps.camps.models import Squad


class SquadUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Squad
    template_name = 'admin_interface/update_squad.html'
    form_class = UpdateSquadModelForm

    def get_success_url(self):
        get_squad = Squad.objects.get(id=self.object.id)
        camp_id = get_squad.camp_id
        return '/squads/list/?camp={}'.format(camp_id)

apps/reservation/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class ReservationsListView(TemplateView):
    template_name = 'admin_interface/reservations.html'

apps/stats/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class StatsTestView(TemplateView):
    template_name = 'admin_interface/stats.html'

templates/admin_interface/add_advantage.html
{% extends 'admin_interface/base.html' %}
{% load static %}

{% block content %}
    <div class="main-content" id="panel">
        {% include "admin_interface/components/navbar.html" %}
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <h3 style="margin-left: 25px;font-weight: bold;font-size: 28px;text-align: center;"
                    class="heading-small text-muted mb-4">Xususiyat qo'shish</h3>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="form-control-label" for="input-title">Xususiyat nomi</label>
                                <input name="title" type="text" id="input-title" class="form-control" value="">
                            </div>
                        </div>
                    </div>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Qo'shish</button>
                </div>
                <hr class="my-4"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/admin_interface/add_moderator.html
{% extends 'admin_interface/base.html' %}
{% load static %}

{% block content %}
    <div class="main-content" id="panel">
        {% include "admin_interface/components/navbar.html" %}

        <div class="card-body">
            <form>
                <h3 style="margin-left: 25px;font-weight: bold;font-size: 28px;text-align: center;"
                    class="heading-small text-muted mb-4">Moderator qo'shish</h3>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="form-control-label" for="input-username">Login</label>
                                <input name="name" type="text" id="input-username" class="form-control" value="">
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="form-control-label" for="input-email">Parol</label>
                                <input name="cost" type="email" id="input-email" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="form-control-label" for="input-email">Tegishli shahar/viloyat</label>
                                <select class="form-control">
                                    <option value="2">Toshkent shahar</option>
                                    <option value="">Toshkent viloyat</option>
                                    <option value="">Farg'ona</option>
                                    <option value="">Namangan</option>
                                    <option value="">Andijon</option>
                                    <option value="">Jizzax</option>
                                    <option value="">Sirdaryo</option>
                                    <option value="">Qashqadaryo</option>
                                    <option value="">Samarqand</option>
                                    <option value="">Buxoro</option>
                                    <option value="">Surxandaryo</option>
                                    <option value="">Xorazm</option>
                                    <option value="">Navoiy</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Qo'shish</button>
                </div>
                <hr class="my-4"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/admin_interface/placement.html
{% extends 'admin_interface/base.html' %}
{% load static %}

{% block content %}
    <div class="main-content" id="panel">
        <!-- Topnav -->
        {% include "admin_interface/components/navbar.html" %}
        <div class="container-fluid mt--6">
            <div class="row" style="margin-top: 102px;">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h2 style="text-transform: uppercase" class="mb-0">I-Smena bo'yicha joylashuv </h2>
                                </div>
                                <div class="col text-right">

                                    <div>
                                        <a style="font-size: 15px;float: right;margin-top: 1px;padding: 9px 7px 10px 8px;" href="/add_placement/" class="btn btn-sm btn-primary">
                                            <i style="font-size: 13px;" class="fa fa-plus"></i>
                                            Joylashuv qo'shish
                                        </a>
                                    </div>
                                    <div style="float: right">
                                        <select style="    margin-right: 56px;margin-left: -35px;" class="form-control" name="shift" id="">
                                            <option value="1">I-Smena</option>
                                            <option value="2">II-Smena</option>
                                            <option value="3">III-Smena</option>
                                            <option value="4">IV-Smena</option>
                                        </select>
                                    </div>



                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <!-- Projects table -->
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">

                                <tr>
                                    <th style="font-size: 15px; font-weight: bold" scope="col"
                                        class="table-header-custom">Bola F.I
                                    </th>
                                    <th style="font-size: 15px; font-weight: bold" scope="col" class="table_header">
                                        Yosh
                                    </th>

                                    <th style="font-size: 15px; font-weight: bold" scope="col" class="table_header">
                                        Otryad
                                    </th>
                                    <th style="font-size: 15px; font-weight: bold" scope="col" class="table_header">
                                         Koyka
                                    </th>

                                    <th style="font-size: 15px; font-weight: bold" scope="col" class="table_header">
                                        Boshqaruv
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for placement in all_placements %}
                                    <tr class="table-content">

                                        <th scope="row">
                                          {{ placement.child_first_name }} {{ placement.child_last_name }}
                                        </th>
                                        <td>
                                         {{ placement.birth_year }}
                                        </td>

                                        <td>
                                            <a href="#" data-toggle="modal" data-target="#exampleModalCenter5"> {{ placement.squad }}</a>
                                        </td>
                                        <td>
                                            {{ placement.bunk }}
                                        </td>

                                        <td>
                                            <a style="font-size: 15px;" href="/camps/detail/" class="btn btn-sm btn-primary">
                                                <i style="font-size: 13px;" class="fa fa-pencil-square-o"></i>
                                                Tahrirlash
                                            </a>

                                        </td>
                                    </tr>
                                    <div class="modal fade" id="exampleModalCenter5" tabindex="-1" role="dialog"
                                         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 align="center" class="modal-title" id="exampleModalLongTitle">{{ placement.squad }} Otryad</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                  <p><b style="font-weight: bold">Jins: </b> {{ placement.squad.gender }}</p>
                                                  <p><b style="font-weight: bold">Sig'imi: </b> {{ placement.squad.capacity }}</p>

                                                    <div class="row">
                                                        <div class="col-md-6">

                                                            <p> <b style="font-weight: bold">Yetakchi: </b>
                                                                {% for squad_leader in placement.squad.squadleaders_set.all %}
                                                                    {% if squad_leader.leader_type == 'leader' %}
                                                                        {{ squad_leader }} ({{ squad_leader.phone_number }})
                                                                    {% endif %}

                                                            </p>
                                                        </div>
                                                                {% endfor %}

                                                        <p> <b style="font-weight: bold">Tarbiyachi: </b>
                                                            {% for squad_leader in placement.squad.squadleaders_set.all %}
                                                                {% if squad_leader.leader_type == 'educator' %}
                                                                    {{ squad_leader }} <br>
                                                                    ({{ squad_leader.phone_number }})
                                                                {% endif %}
                                                            {% endfor %}
                                                        </p>
                                                    </div>




                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin_interface/update_advantage.html
{% extends 'admin_interface/base.html' %}
{% load static %}

{% block content %}
    <div class="main-content" id="panel">
        {% include "admin_interface/components/navbar.html" %}

        <div class="card-body">
            <form method="post">

                {% csrf_token %}
                <h3 style="margin-left: 25px;font-weight: bold;font-size: 28px;text-align: center;"
                    class="heading-small text-muted mb-4">Xususiyatni Tahrirlash</h3>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="form-control-label" for="input-title">Xususiyat nomi</label>
                                <input name="title" type="text" id="input-title" class="form-control" value="{{ object.title }}">
                            </div>
                        </div>

                    </div>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <button type="submit" class="btn btn-primary">Qo'shish</button>
                </div>
                <hr class="my-4"/>
            </form>
        </div>
    </div>
{% endblock %}